### ISSUE TITLE
Couldn't load in.

### ISSUE THREAD

**Issue by Anapropriate** [adam9899/Issues#442] opened 2020-04-09 15:03 UTC
https://paste.dimdev.org/fumubuveqi.mccrash

**Comment by Charismara** [comment] 2020-04-09 15:16
It's an OutOfMemoryError. Allocate more RAM (~5.5 GB should be enough to play, 8 GB would be better)

**Comment by Charismara** [comment] 2020-04-09 15:26
@Anapropriate If the problem is solved pls close this issue

**Closed as completed** 2020-04-09 15:45 UTC
